meta_title: "Stick to it! The app that helps you reach your life goals"
meta_description: "Create a habit in 21 days. Make your life as pretty as it looks on Instagram."
meta_image: "stick_to_it.png" # an image in this folder app/assets/images/
