# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f824a89aaa12743e8f279e6a76371ec49ede5ef90744823583f4383cb8a46f48d9bbf6896b581215a9c45b2532bd1e5facb8dc80fdb727ec23f51ab259bdaa4

test:
  secret_key_base: 5d88fc2b5539922fecb7288195040fdc501f5a76b1fccbcbc9bb334a0807d1325ba115fa62c8d11e2c5afc00d31ad24aca9887be4061cffd558d8f793fc27eb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
