# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# Achievement.destroy_all
# Challenge.destroy_all
# LifeGoal.destroy_all
# Blog.destroy_all

zen = LifeGoal.where(name: "Be more zen").first_or_create
healthy = LifeGoal.where(name: "Live healthier").first_or_create
productive = LifeGoal.where(name: "Be more productive").first_or_create

plug = Challenge.where(name: "Unplug before 10", description: "Don't open up your laptop, switch of your phone or tablet after 10pm, read a book, talk to your roommates or call it an early night", life_goal: zen).first_or_create
laugh = Challenge.where(name: "Laugh everyday for 5 minutes", description: "Watch your favourite comedy series or call your friend and ask if they can tell you a good joke", life_goal: zen).first_or_create
yoga = Challenge.where(name: "Learn a yoga-routine", description: "learn a yoga-routine you can practise for the next 21 days", life_goal: zen).first_or_create
meditate = Challenge.where(name: "Meditate", description: "Take time to meditate for the next 21 days", life_goal: zen).first_or_create
grateful = Challenge.where(name: "Be grateful", description: "Pick one thing you're grateful for everyday, write it down in a notebook every night before you go to sleep", life_goal: zen).first_or_create
intention = Challenge.where(name: "Set an intention", description: "Set a positive intention for your day every morning before you leave the house", life_goal: zen).first_or_create

office = Challenge.where(name: "Clear your workspace", description: "Deal with a cluttered workspace once and for all, reorganize your office", life_goal: productive).first_or_create
focus = Challenge.where(name: "Have a single purpose focus", description: "Pick one thing and do that one thing—and only that one thing—better than anyone else ever could.", life_goal: productive).first_or_create
sleeps = Challenge.where(name: "Get plenty of sleep", description: "Sleep 8 hours per night minimum", life_goal: productive).first_or_create
no = Challenge.where(name: "Learn to say no", description: "Become the opposite of Jim Carrey in Yes Man", life_goal: productive).first_or_create
phone = Challenge.where(name: "Cancel out unnecessary phone time", description: "Turn of your push notifications", life_goal: productive).first_or_create
facebook = Challenge.where(name: "Don't use Facebook for 21 days", description: "Don't use Facebook for 21 days", life_goal: productive).first_or_create

sugar = Challenge.where(name: "No sugar for 21 days", description: "Take processed sugars out of your diet", life_goal: healthy).first_or_create
banana = Challenge.where(name: "Eat bananas", description: "bananas are superhealthy, monkeys also eat it.", life_goal: healthy).first_or_create
cook = Challenge.where(name: "Cook healthy recipes", description: "Choose 21 healthy recipes to cook for the next days", life_goal: healthy).first_or_create
walk = Challenge.where(name: "Take a walk on the wild side", description: "Take a half hour walk during lunch time", life_goal: healthy).first_or_create
alcohol = Challenge.where(name: "No alcohol for 21 days", description: "Don't drink alcohol for the next 21 days", life_goal: healthy).first_or_create

blog1 = Blog.where(title: "Letterpress", intro: "PBR&B tilde humblebrag mlkshk. Ennui chambray godard, migas wolf vaporware nisi etsy mustache officia polaroid cornhole XOXO cupidatat gentrify. Sapiente drinking vinegar activated charcoal hashtag, pabst four dollar toast bicycle rights. Flannel reprehenderit swag, vape ugh wayfarers affogato next level. Nisi esse tumeric lumbersexual skateboard. Hell of vegan et bicycle rights. Williamsburg lyft squid, aliquip tattooed truffaut XOXO.", content: "Distillery velit chia stumptown next level leggings. Kombucha williamsburg vinyl, tattooed meggings small batch activated charcoal commodo echo park. Neutra before they sold out hammock esse, mixtape commodo sustainable. Art party nesciunt waistcoat subway tile velit non. Knausgaard man bun plaid, exercitation adipisicing esse unicorn tattooed artisan prism try-hard marfa humblebrag. Slow-carb viral jianbing, prism migas franzen health goth you probably haven't heard of them kickstarter deep v fap mlkshk esse chia bitters. Laborum gochujang enim, vaporware subway tile tofu occaecat actually.

La croix marfa irony, adipisicing eiusmod voluptate vegan. Letterpress direct trade keytar, ut knausgaard laborum raclette exercitation cillum poke. Tempor gochujang you probably haven't heard of them exercitation. Kale chips bicycle rights kogi chambray quis vaporware. Live-edge chambray YOLO tacos, in slow-carb marfa swag vaporware echo park gochujang activated charcoal cronut retro id. Nisi incididunt culpa blog, lomo fingerstache leggings fashion axe man bun. Asymmetrical ad skateboard, chartreuse fashion axe cold-pressed officia pok pok.

PBR&B XOXO beard, normcore cardigan woke portland hoodie. Venmo microdosing semiotics gluten-free, pok pok hell of 3 wolf moon four dollar toast wayfarers. Craft beer irure la croix organic, fap jean shorts air plant poutine disrupt minim. Eu 3 wolf moon locavore cold-pressed banh mi taxidermy direct trade farm-to-table gluten-free, duis eiusmod. Exercitation cronut ramps laborum bespoke ea stumptown, you probably haven't heard of them yr pickled intelligentsia labore celiac. Microdosing marfa glossier sartorial. Pitchfork meh enim vexillologist, ramps green juice dolore deserunt fugiat.").first_or_create

blog2 = Blog.where(title: "Letterpress2", intro: "PBR&B tilde humblebrag mlkshk. Ennui chambray godard, migas wolf vaporware nisi etsy mustache officia polaroid cornhole XOXO cupidatat gentrify. Sapiente drinking vinegar activated charcoal hashtag, pabst four dollar toast bicycle rights. Flannel reprehenderit swag, vape ugh wayfarers affogato next level. Nisi esse tumeric lumbersexual skateboard. Hell of vegan et bicycle rights. Williamsburg lyft squid, aliquip tattooed truffaut XOXO.", content: "Distillery velit chia stumptown next level leggings. Kombucha williamsburg vinyl, tattooed meggings small batch activated charcoal commodo echo park. Neutra before they sold out hammock esse, mixtape commodo sustainable. Art party nesciunt waistcoat subway tile velit non. Knausgaard man bun plaid, exercitation adipisicing esse unicorn tattooed artisan prism try-hard marfa humblebrag. Slow-carb viral jianbing, prism migas franzen health goth you probably haven't heard of them kickstarter deep v fap mlkshk esse chia bitters. Laborum gochujang enim, vaporware subway tile tofu occaecat actually.

La croix marfa irony, adipisicing eiusmod voluptate vegan. Letterpress direct trade keytar, ut knausgaard laborum raclette exercitation cillum poke. Tempor gochujang you probably haven't heard of them exercitation. Kale chips bicycle rights kogi chambray quis vaporware. Live-edge chambray YOLO tacos, in slow-carb marfa swag vaporware echo park gochujang activated charcoal cronut retro id. Nisi incididunt culpa blog, lomo fingerstache leggings fashion axe man bun. Asymmetrical ad skateboard, chartreuse fashion axe cold-pressed officia pok pok.

PBR&B XOXO beard, normcore cardigan woke portland hoodie. Venmo microdosing semiotics gluten-free, pok pok hell of 3 wolf moon four dollar toast wayfarers. Craft beer irure la croix organic, fap jean shorts air plant poutine disrupt minim. Eu 3 wolf moon locavore cold-pressed banh mi taxidermy direct trade farm-to-table gluten-free, duis eiusmod. Exercitation cronut ramps laborum bespoke ea stumptown, you probably haven't heard of them yr pickled intelligentsia labore celiac. Microdosing marfa glossier sartorial. Pitchfork meh enim vexillologist, ramps green juice dolore deserunt fugiat.").first_or_create

blog3 = Blog.where(title: "Letterpress3", intro: "PBR&B tilde humblebrag mlkshk. Ennui chambray godard, migas wolf vaporware nisi etsy mustache officia polaroid cornhole XOXO cupidatat gentrify. Sapiente drinking vinegar activated charcoal hashtag, pabst four dollar toast bicycle rights. Flannel reprehenderit swag, vape ugh wayfarers affogato next level. Nisi esse tumeric lumbersexual skateboard. Hell of vegan et bicycle rights. Williamsburg lyft squid, aliquip tattooed truffaut XOXO.", content: "Distillery velit chia stumptown next level leggings. Kombucha williamsburg vinyl, tattooed meggings small batch activated charcoal commodo echo park. Neutra before they sold out hammock esse, mixtape commodo sustainable. Art party nesciunt waistcoat subway tile velit non. Knausgaard man bun plaid, exercitation adipisicing esse unicorn tattooed artisan prism try-hard marfa humblebrag. Slow-carb viral jianbing, prism migas franzen health goth you probably haven't heard of them kickstarter deep v fap mlkshk esse chia bitters. Laborum gochujang enim, vaporware subway tile tofu occaecat actually.

La croix marfa irony, adipisicing eiusmod voluptate vegan. Letterpress direct trade keytar, ut knausgaard laborum raclette exercitation cillum poke. Tempor gochujang you probably haven't heard of them exercitation. Kale chips bicycle rights kogi chambray quis vaporware. Live-edge chambray YOLO tacos, in slow-carb marfa swag vaporware echo park gochujang activated charcoal cronut retro id. Nisi incididunt culpa blog, lomo fingerstache leggings fashion axe man bun. Asymmetrical ad skateboard, chartreuse fashion axe cold-pressed officia pok pok.

PBR&B XOXO beard, normcore cardigan woke portland hoodie. Venmo microdosing semiotics gluten-free, pok pok hell of 3 wolf moon four dollar toast wayfarers. Craft beer irure la croix organic, fap jean shorts air plant poutine disrupt minim. Eu 3 wolf moon locavore cold-pressed banh mi taxidermy direct trade farm-to-table gluten-free, duis eiusmod. Exercitation cronut ramps laborum bespoke ea stumptown, you probably haven't heard of them yr pickled intelligentsia labore celiac. Microdosing marfa glossier sartorial. Pitchfork meh enim vexillologist, ramps green juice dolore deserunt fugiat.").first_or_create

blog4 = Blog.where(title: "Letterpress4", intro: "PBR&B tilde humblebrag mlkshk. Ennui chambray godard, migas wolf vaporware nisi etsy mustache officia polaroid cornhole XOXO cupidatat gentrify. Sapiente drinking vinegar activated charcoal hashtag, pabst four dollar toast bicycle rights. Flannel reprehenderit swag, vape ugh wayfarers affogato next level. Nisi esse tumeric lumbersexual skateboard. Hell of vegan et bicycle rights. Williamsburg lyft squid, aliquip tattooed truffaut XOXO.", content: "Distillery velit chia stumptown next level leggings. Kombucha williamsburg vinyl, tattooed meggings small batch activated charcoal commodo echo park. Neutra before they sold out hammock esse, mixtape commodo sustainable. Art party nesciunt waistcoat subway tile velit non. Knausgaard man bun plaid, exercitation adipisicing esse unicorn tattooed artisan prism try-hard marfa humblebrag. Slow-carb viral jianbing, prism migas franzen health goth you probably haven't heard of them kickstarter deep v fap mlkshk esse chia bitters. Laborum gochujang enim, vaporware subway tile tofu occaecat actually.

La croix marfa irony, adipisicing eiusmod voluptate vegan. Letterpress direct trade keytar, ut knausgaard laborum raclette exercitation cillum poke. Tempor gochujang you probably haven't heard of them exercitation. Kale chips bicycle rights kogi chambray quis vaporware. Live-edge chambray YOLO tacos, in slow-carb marfa swag vaporware echo park gochujang activated charcoal cronut retro id. Nisi incididunt culpa blog, lomo fingerstache leggings fashion axe man bun. Asymmetrical ad skateboard, chartreuse fashion axe cold-pressed officia pok pok.

PBR&B XOXO beard, normcore cardigan woke portland hoodie. Venmo microdosing semiotics gluten-free, pok pok hell of 3 wolf moon four dollar toast wayfarers. Craft beer irure la croix organic, fap jean shorts air plant poutine disrupt minim. Eu 3 wolf moon locavore cold-pressed banh mi taxidermy direct trade farm-to-table gluten-free, duis eiusmod. Exercitation cronut ramps laborum bespoke ea stumptown, you probably haven't heard of them yr pickled intelligentsia labore celiac. Microdosing marfa glossier sartorial. Pitchfork meh enim vexillologist, ramps green juice dolore deserunt fugiat.").first_or_create
